/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef FUU_PRIVATE_H
#define FUU_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.0.1.379"
#define VER_MAJOR	0
#define VER_MINOR	0
#define VER_RELEASE	1
#define VER_BUILD	379
#define COMPANY_NAME	"xTCry"
#define FILE_VERSION	"0.0.1.379"
#define FILE_DESCRIPTION	"My xTCry PaintLoL"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"0.0.1.379"

#endif /*FUU_PRIVATE_H*/
